# Generated by Django 4.2.11 on 2024-04-30 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desafioadl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtarea',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subtarea',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desafioadl.tarea'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
